# Generated by Django 2.1.15 on 2021-06-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('fatherName', models.CharField(max_length=30)),
                ('className', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
